apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-app
  namespace: pirates
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: priyanka6209/node-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: pirates
  labels:
    app: node-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30026
  selector:
    app: node-app
