apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-deploy
  namespace: pirates
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: priyanka6209/node-app:latest
        ports:
        - containerPort: 80
        
